# Generated by Django 3.2.6 on 2021-09-07 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField(db_column='recom_user')),
                ('sex', models.CharField(db_column='recom_sex', max_length=2)),
                ('age', models.CharField(db_column='recom_age', max_length=3)),
                ('job', models.CharField(db_column='recom_job', max_length=30)),
                ('family_amount', models.CharField(db_column='recom_family_amount', max_length=10)),
                ('food1', models.CharField(db_column='recom_food1', max_length=30)),
                ('food2', models.CharField(db_column='recom_food2', max_length=30)),
                ('food3', models.CharField(db_column='recom_food3', max_length=30)),
                ('item1', models.CharField(db_column='recom_item1', max_length=30)),
                ('item2', models.CharField(db_column='recom_item2', max_length=30)),
                ('item3', models.CharField(db_column='recom_item3', max_length=30)),
                ('mbti', models.CharField(db_column='recom_mbti', max_length=4)),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='store_name', max_length=30)),
                ('tel', models.CharField(db_column='store_tel', max_length=11)),
                ('opentime', models.CharField(db_column='store_open', max_length=20)),
                ('closetime', models.CharField(db_column='store_close', max_length=20)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='product_name', max_length=50)),
                ('intro', models.TextField(db_column='product_intro')),
                ('weight', models.CharField(db_column='product_weight', max_length=10)),
                ('origin', models.CharField(db_column='product_origin', max_length=20)),
                ('photo', models.ImageField(db_column='product_photo', upload_to='')),
                ('price', models.PositiveIntegerField(db_column='product_price')),
                ('stock', models.PositiveIntegerField(db_column='product_stock')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.store')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
