# Generated by Django 3.2.6 on 2021-09-07 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(choices=[('E', '친구들 혹은 가족들과 함께 간다.'), ('I', '혼자만의 시간을 즐긴다.')], default=1, max_length=50)),
                ('q2', models.CharField(choices=[('J', '구매할 것들을 목록에 적는다.'), ('P', '시장에 가서 생각한다.')], default=1, max_length=50)),
                ('q3', models.CharField(choices=[('J', '구매할 것들을 적은 목록에 있는 것들 먼저 구매한다.'), ('P', '구경 먼저하고 나중에 필요한 산다.')], default=1, max_length=50)),
                ('q4', models.CharField(choices=[('S', '다른 곳에서 시간 때우다 다시 온다.'), ('N', '새로운 곳에 가본다.')], default=1, max_length=50)),
                ('q5', models.CharField(choices=[('E', '사장님! 여기서 제일 잘나가는 물건 뭐에요?.'), ('I', '나 혼자 쇼핑하고 싶은데...ㅆㅆ;;.')], default=1, max_length=50)),
                ('q6', models.CharField(choices=[('E', '전동시장은 흥정하는 맛이지~~.'), ('I', '가격이 적힌대로 산다.')], default=1, max_length=50)),
                ('q7', models.CharField(choices=[('S', "'어 저걸로 살까?' 잘나가는 메뉴를 고른다"), ('N', "'그렇군!' 내가 먹고싶은 것을 고른다.")], default=1, max_length=50)),
                ('q8', models.CharField(choices=[('S', '다른 상점과 비교하고 구매한다.'), ('N', '이거 괜찮은데?. 그냥 바로 구매.')], default=1, max_length=50)),
                ('q9', models.CharField(choices=[('T', '평소처럼 카드를 내민다.'), ('F', "'상인분들이 현금결제를 하면 좋아하겠지?' 현금결제한다.")], default=1, max_length=50)),
                ('q10', models.CharField(choices=[('J', 'SNS를 검색해 맛집을 찾는다.'), ('P', '맛있는 냄새를 따라 식당을 찾아간다.')], default=1, max_length=50)),
                ('q11', models.CharField(choices=[('T', '각자 먹고 싶은 메뉴 먹자!'), ('F', '그래 너희 먹고 싶은거 먹자~')], default=1, max_length=50)),
                ('q12', models.CharField(choices=[('T', '필요한 물건 저렴한 가격에 잘 구매했네!'), ('F', '시장에서 흥정도 하고 사진도 찍고 뿌듯하고 즐거운 하루였어!')], default=1, max_length=50)),
                ('mbti', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('F', '여성'), ('M', '남성')], default='F', max_length=1)),
                ('age', models.CharField(db_column='customer_age', max_length=3)),
                ('tel', models.CharField(db_column='customer_tel', max_length=11)),
                ('address', models.CharField(db_column='customer_address', max_length=200)),
                ('job', models.CharField(choices=[('학생또는취업준비생', '학생 또는 취업준비생'), ('가정주부', '가정주부'), ('직장인', '직장인'), ('기타', '기타')], default=1, max_length=50)),
                ('family_amount', models.PositiveIntegerField(choices=[(1, '1명'), (2, '2명'), (3, '3명'), (4, '4명'), (5, '5명 이상')], default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(choices=[('간이서랍', '간이서랍'), ('공구', '공구'), ('냄비', '냄비'), ('바구니', '바구니'), ('볼펜', '볼펜'), ('부채', '부채'), ('세제', '세제'), ('수건', '수건'), ('시계', '시계'), ('이불', '이불'), ('조명/스탠드', '조명/스탠드'), ('청소용밀대', '청소용밀대'), ('칼', '칼'), ('커텐', '커텐'), ('쿠션', '쿠션'), ('건강기능식품', '건강기능식품'), ('슬리퍼', '슬리퍼'), ('안경', '안경'), ('양말', '양말'), ('운동복', '운동복'), ('잠옷', '잠옷'), ('팔토시', '팔토시'), ('편한바지', '편한바지'), ('화장품', '화장품'), ('모종(씨)/화분', '모종(씨)/화분'), ('수영모', '수영모'), ('통기타', '통기타')], default=1, max_length=20)),
                ('item2', models.CharField(choices=[('간이서랍', '간이서랍'), ('공구', '공구'), ('냄비', '냄비'), ('바구니', '바구니'), ('볼펜', '볼펜'), ('부채', '부채'), ('세제', '세제'), ('수건', '수건'), ('시계', '시계'), ('이불', '이불'), ('조명/스탠드', '조명/스탠드'), ('청소용밀대', '청소용밀대'), ('칼', '칼'), ('커텐', '커텐'), ('쿠션', '쿠션'), ('건강기능식품', '건강기능식품'), ('슬리퍼', '슬리퍼'), ('안경', '안경'), ('양말', '양말'), ('운동복', '운동복'), ('잠옷', '잠옷'), ('팔토시', '팔토시'), ('편한바지', '편한바지'), ('화장품', '화장품'), ('모종(씨)/화분', '모종(씨)/화분'), ('수영모', '수영모'), ('통기타', '통기타')], default=1, max_length=20)),
                ('item3', models.CharField(choices=[('간이서랍', '간이서랍'), ('공구', '공구'), ('냄비', '냄비'), ('바구니', '바구니'), ('볼펜', '볼펜'), ('부채', '부채'), ('세제', '세제'), ('수건', '수건'), ('시계', '시계'), ('이불', '이불'), ('조명/스탠드', '조명/스탠드'), ('청소용밀대', '청소용밀대'), ('칼', '칼'), ('커텐', '커텐'), ('쿠션', '쿠션'), ('건강기능식품', '건강기능식품'), ('슬리퍼', '슬리퍼'), ('안경', '안경'), ('양말', '양말'), ('운동복', '운동복'), ('잠옷', '잠옷'), ('팔토시', '팔토시'), ('편한바지', '편한바지'), ('화장품', '화장품'), ('모종(씨)/화분', '모종(씨)/화분'), ('수영모', '수영모'), ('통기타', '통기타')], default=1, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPrefer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food1', models.CharField(choices=[('냉채족발', '냉채족발'), ('닭볶음탕', '닭볶음탕'), ('돈까스', '돈까스'), ('불고기', '불고기'), ('뼈해장국', '뼈해장국'), ('삼겹살', '삼겹살'), ('설렁탕', '설렁탕'), ('제육볶음', '제육볶음'), ('치킨', '치킨'), ('(물)회', '(물)회'), ('생선구이', '생선구이'), ('아구찜', '아구찜'), ('해물칼국수', '해물칼국수'), ('해물탕', '해물탕'), ('꽈배기', '꽈배기'), ('냉면', '냉면'), ('떡볶이', '떡볶이'), ('모둠전(부침개)', '모둠전(부침개)'), ('붕어빵', '붕어빵'), ('샐러드(야채)', '샐러드(야채)'), ('수박화채', '수박화채'), ('순대', '순대'), ('식혜', '식혜'), ('잔치국수', '잔치국수'), ('짜장면', '짜장면')], default=1, max_length=20)),
                ('food2', models.CharField(choices=[('냉채족발', '냉채족발'), ('닭볶음탕', '닭볶음탕'), ('돈까스', '돈까스'), ('불고기', '불고기'), ('뼈해장국', '뼈해장국'), ('삼겹살', '삼겹살'), ('설렁탕', '설렁탕'), ('제육볶음', '제육볶음'), ('치킨', '치킨'), ('(물)회', '(물)회'), ('생선구이', '생선구이'), ('아구찜', '아구찜'), ('해물칼국수', '해물칼국수'), ('해물탕', '해물탕'), ('꽈배기', '꽈배기'), ('냉면', '냉면'), ('떡볶이', '떡볶이'), ('모둠전(부침개)', '모둠전(부침개)'), ('붕어빵', '붕어빵'), ('샐러드(야채)', '샐러드(야채)'), ('수박화채', '수박화채'), ('순대', '순대'), ('식혜', '식혜'), ('잔치국수', '잔치국수'), ('짜장면', '짜장면')], default=1, max_length=20)),
                ('food3', models.CharField(choices=[('냉채족발', '냉채족발'), ('닭볶음탕', '닭볶음탕'), ('돈까스', '돈까스'), ('불고기', '불고기'), ('뼈해장국', '뼈해장국'), ('삼겹살', '삼겹살'), ('설렁탕', '설렁탕'), ('제육볶음', '제육볶음'), ('치킨', '치킨'), ('(물)회', '(물)회'), ('생선구이', '생선구이'), ('아구찜', '아구찜'), ('해물칼국수', '해물칼국수'), ('해물탕', '해물탕'), ('꽈배기', '꽈배기'), ('냉면', '냉면'), ('떡볶이', '떡볶이'), ('모둠전(부침개)', '모둠전(부침개)'), ('붕어빵', '붕어빵'), ('샐러드(야채)', '샐러드(야채)'), ('수박화채', '수박화채'), ('순대', '순대'), ('식혜', '식혜'), ('잔치국수', '잔치국수'), ('짜장면', '짜장면')], default=1, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
